### ISSUE TITLE
Best way customize the toolbar

### ISSUE THREAD

**Issue by willkramer** [kwinyyyc/strapi-plugin-wysiwyg-react-md-editor#19]
What is the best way to customize the React MD Editor toolbar? I know I can edit the code in `ReactMdEditor/index.js`
https://github.com/kwinyyyc/strapi-plugin-wysiwyg-react-md-editor/blob/62f135e15463bb9d96480c05f055be1aa1119e6a/admin/src/components/ReactMdEditor/index.js#L108-L151

Is there anyway to inject edits through the Strapi plugins.js file?

**Comment by kwinyyyc** [comment]
Currently there is no way to customize the toolbar.

The easier way, it can be done via loading config from `config/plugins.js`

In the long run, it might be useful creating a setting UI for the plugin.

I will give it a `feature request` tag for now.

PR welcome if you are interested to work on it

**Comment by kwinyyyc** [comment]
In case anyone is still interested in it, it is released in [v4.5.0](https://www.npmjs.com/package/strapi-plugin-wysiwyg-react-md-editor/v/4.5.0)
