### ISSUE TITLE
Full screen editor needs higher z-index

### ISSUE THREAD

**Issue by robfoulsham** [kwinyyyc/strapi-plugin-wysiwyg-react-md-editor#28]
element  w-md-editor.w-md-editor-show-live.w-md-editor-fullscreen is behind the strapi-sticky-header and prevents the user from being able to exit this view without losing their work. Then if 'back' is selected, the user can no longer scroll within the content type editor.

Please set the z-index of this editor view much higher so that it is always possible to exit and return to the main content editing area (or fix it however you see fit!)

<img width="950" alt="image" src="https://github.com/kwinyyyc/strapi-plugin-wysiwyg-react-md-editor/assets/60383723/09358688-b0e9-443f-972a-2dbd18ccb2cc">

**Comment by kwinyyyc** [comment]
@robfoulsham which strapi version are you using? from what I see strapi alert is dismissed after several seconds and it appears in the middle top of the screen

**Comment by robfoulsham** [comment]
@kwinyyyc the issue is present on both 4.15.5 and 4.19.0.

The banner is there whenever you're scrolled down on the main edit page and disappears once you scroll back up to the top. (if you don't enter the full screen MD editor view)

**Comment by kwinyyyc** [comment]
I have tried using Strapi 4.19.0 with `"strapi-plugin-wysiwyg-react-md-editor": "^4.5.0"` and can't replicate the issue, the save panel stack nicely on top of the editor. Please try to update the plugin version.

![image](https://github.com/kwinyyyc/strapi-plugin-wysiwyg-react-md-editor/assets/8462684/c6412b57-fe71-4c41-9402-078b5548bdd0)

**Comment by robfoulsham** [comment]
Hey there,

Yes that is exactly the problem, how do you exit from this view to go back to editing other fields in the content?

Steps to reproduce:

- open content type for editing 
- scroll down so that banner appears
- click full screen editor view
- try to exit full screen editor view

<img width="1273" alt="image" src="https://github.com/kwinyyyc/strapi-plugin-wysiwyg-react-md-editor/assets/60383723/f5bbb135-ff26-4547-8c1a-5f7913825e35">

<img width="1648" alt="image" src="https://github.com/kwinyyyc/strapi-plugin-wysiwyg-react-md-editor/assets/60383723/05400dfb-4dfd-4467-ba92-6fc122761f9d">

This causes me to be stuck in full screen editor view. the only way to go back is by using the main 'back' button on the banner, which takes me right back to the list of content types. If I then enter the edit view again, I can no longer scroll.

Thanks for your time on this, much appreciate.

**Comment by kwinyyyc** [comment]
@robfoulsham thanks for reporting the issue, I can replicate the issue and have released a new version, please kindly try [v4.5.1](https://www.npmjs.com/package/strapi-plugin-wysiwyg-react-md-editor/v/4.5.1)

**Comment by robfoulsham** [comment]
Brilliant, thank you for fixing it! I'm away from my computer for a couple
of weeks but will update as soon as I'm back and let you know. 👍👍

**Comment by robfoulsham** [comment]
Hi, many thanks for the change, but I'm still experiencing this issue. When I inspect the stick-header, it shows as z-index 10:

<img width="1224" alt="image" src="https://github.com/kwinyyyc/strapi-plugin-wysiwyg-react-md-editor/assets/60383723/2c62df98-5864-4220-b68a-730412eef79a">

Updating the z-index you changed in admin/src/components/ReactMdEditor/index.tsx to 11 seems to fix the issue for me, BUT, disclaimer, I don't see where they are setting the z-index value of 10, and don't really know what I'm talking about. I'm not familiar with frontend projects.  

Setting the z-index to 11 gives me:

<img width="1598" alt="image" src="https://github.com/kwinyyyc/strapi-plugin-wysiwyg-react-md-editor/assets/60383723/deac8afa-df8f-4fc1-a8a1-f69ff3e5a192">

**Comment by kwinyyyc** [comment]
Interestingly when I inspect the `sticky-header` it has z-index of 4, maybe they set it dynamically or set a different value in different Strapi version.

I have publish a beta version which you could test if it works. `https://www.npmjs.com/package/strapi-plugin-wysiwyg-react-md-editor/v/4.5.1-beta.0`

**Comment by robfoulsham** [comment]
Thanks @kwinyyyc that has fixed it for me!

Really appreciate your time on this. Will you be merging that into the main release? Cheers

**Comment by kwinyyyc** [comment]
> Thanks @kwinyyyc that has fixed it for me!
> 
> Really appreciate your time on this. Will you be merging that into the main release? Cheers

I have just released [4.5.2](https://www.npmjs.com/package/strapi-plugin-wysiwyg-react-md-editor/v/4.5.2)
