### ISSUE TITLE
required strapi version 4.9.2?

### ISSUE THREAD

**Issue by hozunlee** [kwinyyyc/strapi-plugin-wysiwyg-react-md-editor#30]
<img width="987" alt="image" src="https://github.com/kwinyyyc/strapi-plugin-wysiwyg-react-md-editor/assets/60101732/fd3b45f3-bde0-4da8-9429-6a19d93a3948">

But strapi version is 4.25.5 now

<img width="582" alt="image" src="https://github.com/kwinyyyc/strapi-plugin-wysiwyg-react-md-editor/assets/60101732/99ddb755-d945-444e-9d61-3147b59630d9">

When doing install, this plugin
```
node_modules/@strapi/strapi
npm ERR!   peer @strapi/strapi@"4.9.2" from strapi-plugin-wysiwyg-react-md-editor@4.5.2
npm ERR!   node_modules/strapi-plugin-wysiwyg-react-md-editor
npm ERR!     strapi-plugin-wysiwyg-react-md-editor@"^4.5.2" from the root project
```

Show error message.

I was forced to install it. ( option -> --forece)

How do I install it?

**Comment by kwinyyyc** [comment]
@hozunlee it should be working on any strapi version > 4.9.2. I have released a [new version](https://www.npmjs.com/package/strapi-plugin-wysiwyg-react-md-editor/v/4.5.3), please give it a try.
